### ISSUE TITLE
Kubernetes cannot probe Management Center for health

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/management-center-docker#16]
Port 8081 is not exposed

Cannot use

```
env:
 - name: hazelcast.mc.healthCheck.enable
    value: true
```

&

```
livenessProbe:
 httpGet:
  path: /hazelcast-mancenter/health
  port: 8081
readinessProbe:
 httpGet:
  path: /hazelcast-mancenter/health
  port: 8081
```
